language: node_js
node-js:
  - lts/*
script:
  - rm -rf dist
  - npm run lint
  - npm run travisBuild

notifications:
  email: false

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: main
    local_dir: ./dist/CoronaUpdate
